version: "3"
services:
  web:
    container_name: php-playground
    build: .
    ports:
      - "8300:80"
    volumes:
      - ./web/:/var/www/html/
    env_file: .env
    networks:
      - webnet
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    # volumes:
    #   - ./.dump:/var/lib/mysql
    networks:
      - webnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8799:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: test
    networks:
      - webnet
networks:
  webnet: